from typing import TypedDict, List, Dict, Optional, Any

class AgentState(TypedDict):
    # The active student we are tutoring
    student_id: str
    
    # The user's original message/question
    user_input: str
    
    # The history of the conversation for context
    chat_history: List[Dict[str, str]]
    
    # Has a misconception been detected by the Diagnoser?
    misconception_detected: bool
    
    # Which concepts were affected by the misconception
    affected_concepts: List[str]
    
    # The paths generated by the Planner
    learning_paths: List[List[str]]
    
    # The final natural language response constructed by the Tutor
    final_response: str
