from typing import TypedDict, List, Dict

class AgentState(TypedDict):
    # The active student we are tutoring
    student_id: str
    
    # The user's original message/question
    user_input: str
    
    # The history of the conversation for context
    chat_history: List[Dict[str, str]]

    # Router decision for the current turn
    route: str

    # Why the router selected the current path
    route_reason: str
    
    # Has a misconception been detected by the Diagnoser?
    misconception_detected: bool
    
    # Which concepts were affected by the misconception
    affected_concepts: List[str]
    
    # The paths generated by the Planner
    learning_paths: List[str]

    # Retrieval context gathered for the tutor
    retrieved_context: str

    # Long-term memory recalled for this turn
    long_term_memory: str
    
    # The final natural language response constructed by the Tutor
    final_response: str
